export const DEN_MCP_ACCESS_TOKEN_EXPIRES_IN_SECONDS = 15 * 60
export const DEN_MCP_REFRESH_TOKEN_EXPIRES_IN_SECONDS = 7 * 24 * 60 * 60
export const DEN_FIRST_PARTY_MCP_TOKEN_TTL_MS = DEN_MCP_REFRESH_TOKEN_EXPIRES_IN_SECONDS * 1000
